services:
  - type: web
    name: job-portal
    env: python
    buildCommand: pip install -r pyproject.toml
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-portal-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: job-portal-db
    databaseName: jobportal
    user: jobportal_user